KBTB
C© Abc
P

QBTB.BOF BTB.PG - -
L0
BSome thing
V105
Sdeu
T1
X*BTBBMPS
F0x000000 -1 0x0000FF -1 0x0000FF -1
IBTB.KI 1 0
IBTB.FI 4 0
Dbtb 1 122582529 16 2
Dbtb_pic 620000000 629000000 32 2
Dbtb_tab 660000000 669000000 96 2
Dbtb_tim 670000000 671000000 96 6 100 0 1009

GPERSON|Person|S
GWEB|Web|S
GZEIT|Zeitangabe|Z
GUPDATE|Aktualisierte Einträge|S

GMEDIA|Medientyp|L
gMEDIA|Tabellen|T
gMEDIA|Bilder|BB

GWISSEN|Wissensgebiet|L
gWISSEN|Allgemeine und angewandte Biologie|69

E
